---
author: Peter Reithofer
title: Decomposition
date: "2022-01-19"
---

# At a glance
Concept to decompose infinite variable domain into finitely many,
truth-invariant intervals.

# Algebra concepts
* **Degree**:
  * Degree of monomial is sum of exponents.
  * Degree of polynomial is max degree of monomials in canonical form.
* **(real/complex) Root**: $\vec{x} \in (\mathbb{R} / \mathbb{C})$ such that $p(\vec{x}) = 0$
* **Finite abstraction**: finite set of points that contains one point from each sign invariant
    region from $p$

# Algebra facts
* Every *univariate* poly $p$ of degree $d$ has exactly $d$ complex roots and thus at most
  $d$ real roots.
* Sign of $p$ is invariant between two successive roots.
* We can partition $\mathbb{R}$ into at most $2d + 1$ *sign invariant* regions for $p$.

# Invariant regions of single poly
# Invariant regions of multiple polys
# Application
Given a *finite abstraction* of a poly we can easily check if it can satisfy a constraint
by pluging in all *sample points* from the abstraction and evaluating the formula.