---
author: "Peter Reithofer"
title: "Cylindrical algebraic decomposition"
date: "2022-01-19"
format:
  html:
    toc: true
    toc-depth: 5
    number-sections: true
    self-contained: true
---

\newcommand{\R}{\mathbb{R}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\phi}{\varphi}

## At a glance
* complete (only complete procedure for QFNRA one in this lecture)
* only handles set of constraints
* generates finite set of samples that include all sign invariant regions
* double exponential runtime


## Terminology

Region
: non-empty connected subset of $\R^n$.

Decomposition
: is finite partition where each cell (part of partition) is a region.

::: {#def-cad}
### Cylindrical Algebraic Decomposition
A CAD is a decomposition that is:

* (semi)-**algebraic**: if each cell can be constructed from poly varieties
  using:
    * finite union
    * intersection
    * complementation
* **cylindrical**: either $n=1$ or any projection to lower dimension is
  cylindrical

CAD of poly is CAD whose cells are sign invariant.
:::

::: {#def-real-algebraic-numbers}
### Real Algebraic Numbers
A number $a \in \R$ is called real algebraic iff.
there exists poly $p \in \Q[x]$ such that $p(a) = 0$.

We represent $a$ by $(p, I)$ where $I \subseteq \R$ is *open* or a *point*
and $p$ has only on real root in $I$.
:::

::: {#def-cauchy-bound}
### Cauchy Bound
For $p \in \Q[x]$ with coefficients $a_1,...,a_k$ and leading coeff $l$,
the *cauchy bound* 

$$C := 1 + \max{\frac{|a_i|}{l}}$$
:::

::: {#lem-cauchy-bound}
### Cauchy Bound application
We know that all real roots of $p$ are in $[-C, C]$.

\
:::

## Sturm sequence

::: {#def-sturm-sequence}
### Sturm sequence
Let $p \in \Q[x]$ where the factorisation of $p$ has no repreating factors.
Then the **sturm sequence** of $p$ is given by:

* $p_0 = p$
* $p_1 = p'$
* $p_i = -\text{rem}(p_{i-2}, p_{i-1})$
* ...
* $p_k = 0$
:::

::: {#lem-sturm-sequence-application}
### Sturm sequence application
Let $p \in \Q[x]$ and $(p_0,...,p_k)$ it's sturm sequence.
Further let $\sigma(x)$ be the number of sign changes in 
$(p_0(x), p_1(x),..., p_k(x))$.

Then we know that the number of real roots of $p$ in $(a, b]$ is $\sigma(a) - \sigma(b)$.
:::

[Sturm Sequence Calculator](https://planetcalc.com/7719/)

:::{.callout-important}
In exam sturm sequence will be given!
:::

## Case of $\R$

**Algorithm**:

* Calculate Cauchy Bound $C$
* Start with $r = \{ (-C, C) \}$
* While some interval in $r$ contains more than $1$ real root (calc with Sturm Sequence)
  * split interval

<!-- TODO: what if polys share root??? -->

::: {.callout-note}
Evaluation of polys at algebraic numbers with our representation not handled in
this lecture.
:::

## Case of $\R^n$

Harder because we have potentially infinite varieties.

::: {#def-delineable}
### Delineability
A poly $p$ is *delineable* on a region $R \subseteq \R^{n-1}$ 
iff.
for each $\vec{a} \in R$ the number of:

* roots of $p(\vec{a},x)$
* different roots of $p(\vec{a},x)$
* common roots of $p(\vec{a},x)$

is constant.
:::

### Algo
* projection is black-box
* projection gives set of polys with one variable less such that common zeros
  are cylinder boundaries of higher-dim polys.
* projection is hard. is step which makes algo double exp
* three parts:
  * resultant whose roots cover projections of common roots of two polys
  * discriminant whose roots cover projections of points where number of roots
    of single poly changes
  * coefficients whose roots cover divergence points
  * (cover because they may have additional superflous roots)
  
## Generate infeasible subsets

* Collect the violated constraints for each sample point.
* Calculate covering